import { useEffect, useState } from "react";
import axios from "axios";
import "../../styles/dashboard.css";

const DashboardPage = () => {
  const [orders, setOrders] = useState([]);
  const [deliveries, setDeliveries] = useState([]);
  const [recommendations, setRecommendations] = useState([]);

  const API_URL = import.meta.env.VITE_API_URL || "http://localhost:5000";

  useEffect(() => {
    const fetchDashboardData = async () => {
      try {
        const token = localStorage.getItem("token");

        const [ordersRes, deliveriesRes, recommendationsRes] =
          await Promise.all([
            axios.get(`${API_URL}/api/orders`, {
              headers: { Authorization: `Bearer ${token}` },
            }),
            axios.get(`${API_URL}/api/integration/logistics/delivery-status`),
            axios.get(`${API_URL}/api/integration/forecasting/recommendations`),
          ]);

        setOrders(ordersRes.data.data || []);
        setDeliveries(deliveriesRes.data.data || []);
        setRecommendations(recommendationsRes.data.data || []);
      } catch (err) {
        console.error("Dashboard fetch error:", err);
      }
    };

    fetchDashboardData();
  }, [API_URL]);

  const totalOrders = orders.length;
  const pendingOrders = orders.filter((o) => o.status === "Pending").length;
  const inTransitDeliveries = deliveries.filter(
    (d) => d.status === "In Transit"
  ).length;
  const stockRecommendations = recommendations.length;
  const delayedDeliveries = deliveries.filter((d) => d.status === "Delayed").length;
  const highPriorityRecommendations = recommendations.filter(
    (r) => Number(r.recommendedStock) >= 50
  ).length;

  const recentOrders = orders.slice(0, 5);
  const deliveryUpdates = deliveries.slice(0, 5);
  const stockAlerts = recommendations.slice(0, 5);

  return (
    <div className="dashboard">
      <div className="stats">
        <div className="stat-card">Total Orders: {totalOrders}</div>
        <div className="stat-card">Pending Orders: {pendingOrders}</div>
        <div className="stat-card">
          Deliveries in Transit: {inTransitDeliveries}
        </div>
        <div className="stat-card">
          Stock Recommendations: {stockRecommendations}
        </div>
      </div>

      <div className="grid">
        <div className="card">
          <h3>Operational Summary</h3>

          <div className="summary-list">
            <div className="summary-row">
              <span>Total Orders</span>
              <b>{totalOrders}</b>
            </div>

            <div className="summary-row">
              <span>Pending Orders</span>
              <b>{pendingOrders}</b>
            </div>

            <div className="summary-row">
              <span>In Transit Deliveries</span>
              <b>{inTransitDeliveries}</b>
            </div>

            <div className="summary-row">
              <span>Delayed Deliveries</span>
              <b>{delayedDeliveries}</b>
            </div>
          </div>
        </div>

        <div className="card">
          <h3>Demand Forecasting Summary</h3>

          <div className="summary-list">
            <div className="summary-row">
              <span>Total Recommendations</span>
              <b>{stockRecommendations}</b>
            </div>

            <div className="summary-row">
              <span>High Priority Restocks</span>
              <b>{highPriorityRecommendations}</b>
            </div>

            <div className="summary-row">
              <span>Latest Recommended Item</span>
              <b>{recommendations[0]?.item || "N/A"}</b>
            </div>

            <div className="summary-row">
              <span>Generated By</span>
              <b>{recommendations[0]?.generatedBy || "Forecasting"}</b>
            </div>
          </div>
        </div>
      </div>

      <div className="bottom-grid">
        <div className="small-card">
          <h3>Recent Orders</h3>

          <div className="small-card-scroll">
            {recentOrders.length > 0 ? (
              recentOrders.map((o) => (
                <div className="table-row" key={o._id || o.id}>
                  <span>{o.id}</span>
                  <span>{o.status}</span>
                </div>
              ))
            ) : (
              <p className="empty-text">No recent orders</p>
            )}
          </div>
        </div>

        <div className="small-card">
          <h3>Delivery Updates</h3>

          <div className="small-card-scroll">
            {deliveryUpdates.length > 0 ? (
              deliveryUpdates.map((d) => (
                <div className="table-row" key={d._id || d.orderId}>
                  <span>{d.orderId}</span>
                  <span>{d.status}</span>
                </div>
              ))
            ) : (
              <p className="empty-text">No delivery updates</p>
            )}
          </div>
        </div>

        <div className="small-card">
          <h3>Stock Recommendations</h3>

          <div className="small-card-scroll">
            {stockAlerts.length > 0 ? (
              stockAlerts.map((s) => (
                <div className="table-row" key={s._id}>
                  <span>{s.item}</span>
                  <span>{s.recommendedStock}</span>
                </div>
              ))
            ) : (
              <p className="empty-text">No stock recommendations</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default DashboardPage;